# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       sailfishos-patches-base

# >> macros
BuildArch: noarch
# << macros

Summary:    A set of small and well-maintained patches
Version:    0.0
Release:    1
Group:      Qt/Qt
License:    TODO
URL:        https://github.com/sailfishos-patches/sailfishos-patches-base
Source0:    %{name}-%{version}.tar.bz2
Source100:  sailfishos-patches-base.yaml
Requires:   patchmanager
Obsoletes:   patchmanager-volume-warning
Obsoletes:   roboro-better-calllog

%description
This package contains a set of patches that should 
not cause much harm on the device. 


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
mkdir -p %{buildroot}/usr/share/patchmanager/patches
for f in $(ls maintained); do
cp -r maintained/$f %{buildroot}/usr/share/patchmanager/patches/base-$f
done
# << install pre

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%{_datadir}/patchmanager/patches/base-*
# >> files
# << files
